codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        
    patch:
      default:
        target: auto
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
        only_pulls: false

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/*"
  - "coverage-html/*"
  - "vendor/*"
