<?php
/**
 * @Author            : Die Coding <www.diecoding.com>
 * @Date              : 11 March 2018
 * @Email             : diecoding@gmail.com
 * @Last modified by  : Die Coding <www.diecoding.com>
 * @Last modified time: 15 March 2018
 * @License           : MIT
 * @Copyright         : 2018
 */


/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' does not support labels().' => ' tidak mendukung labels().',
    '\'{class}\' must extend from \'yiibacRule\' or its child class' => '\'{class}\' harus mengacu pada \'yii\\rbac\\Rule\' atau child nya',
    'Activate' => 'Aktifkan',
    'Active' => 'Aktif',
    'Add' => 'Tambah',
    'All User' => 'Semua Pengguna',
    'Application' => 'Aplikasi',
    'Are you sure to delete this item?' => 'Apakah Anda yakin akan menghapus data ini?',
    'Are you sure you want to {label} this user?' => 'Apakah Anda yakin akan {label} pengguna ini?',
    'Assign' => 'Tugas',
    'Assignment' => 'Penugasan',
    'Assignments' => 'Penugasan',
    'Auth Key' => 'Auth Key',
    'Change' => 'Ubah',
    'Change Password' => 'Ubah Kata Sandi',
    'Check your email for further instructions.' => 'Silakan cek surel Anda.',
    'Class Name' => 'Nama Kelas',
    'Create' => 'Tambah',
    'Create Menu' => 'Tambah Menu',
    'Create Rule' => 'Tambah Peraturan',
    'Create {value}' => 'Tambah {value}',
    'Created At' => 'Terdaftar Pada',
    'Data' => 'Data',
    'Delete' => 'Hapus',
    'Description' => 'Deskripsi',
    'Display Name' => 'Nama Lengkap',
    'Email' => 'Surel',
    'Guide' => 'Bantuan',
    'ID' => 'ID',
    'Icon' => 'Ikon',
    'Inactive' => 'Tidak Aktif',
    'Incorrect password.' => 'Kata sandi salah.',
    'Incorrect username or email.' => 'Nama pengguna atau surel salah.',
    'Invalid rule "{value}"' => 'Pengaturan salah "{value}"',
    'Last Login' => 'Terakhir Masuk',
    'Login' => 'Masuk',
    'Loop detected.' => 'Loop terdeteksi.',
    'Menus' => 'Menu',
    'Name' => 'Nama',
    'New password was saved.' => 'Kata sandi berhasil diubah.',
    'New route(s)' => 'Rute baru',
    'Non Activate' => 'Menonaktifkan',
    'Order' => 'Urutan',
    'Parent' => 'Parent',
    'Parent Name' => 'Nama Parent',
    'Password Hash' => 'Hash Sandi',
    'Password Reset Token' => 'Token Reset Sandi',
    'Permission' => 'Perizinan',
    'Permissions' => 'Perizinan',
    'Photo' => 'Foto',
    'Please choose your new password:' => 'Silakan masukan kata sandi baru:',
    'Please fill out the following fields to change password:' => 'Silakan isi semua formulir untuk mengubah kata sandi:',
    'Please fill out the following fields to signup:' => 'Silakan isi semua formulir untuk mendaftar:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Silakan isi surel anda. Token reset kata sandi akan dikirimkan ke surel tersebut.',
    'RBAC' => 'RBAC',
    'Remove' => 'Hapus',
    'Request password reset' => 'Permintaan reset kata sandi',
    'Reset password' => 'Reset kata sandi',
    'Role' => 'Peran',
    'Roles' => 'Peran',
    'Route' => 'Rute',
    'Route "{value}" not found.' => 'Rute "{value}" tidak tersedia.',
    'Routes' => 'Rute',
    'Rule "{value}" does not exists' => 'Peraturan "{value}" tidak tersedia.',
    'Rule Name' => 'Nama Peraturan',
    'Rules' => 'Peraturan',
    'Save' => 'Simpan',
    'Search for assigned' => 'Cari yang sudah ditugaskan',
    'Search for available' => 'Cari yang tersedia',
    'Send' => 'Kirim',
    'Signup' => 'Daftar',
    'Sorry, we are unable to reset password for email provided.' => 'Maaf, kata sandi gagal diubah, ada masalah berkaitan dengan surel.',
    'Status' => 'Status',
    'The requested page does not exist.' => 'Halaman tidak tersedia.',
    'Type' => 'Jenis',
    'Unknown class \'{class}\'' => 'Kelas \'{class}\' tidak diketahui',
    'Update' => 'Ubah',
    'Update Menu' => 'Ubah Menu',
    'Update Rule' => 'Ubah Aturan',
    'Update {value}' => 'Ubah {value}',
    'Updated At' => 'Diubah Pada',
    'User Login' => 'Pengguna Sudah Login',
    'User Not Login' => 'Pengguna Tanpa Login',
    'Username' => 'Nama Pengguna',
    'Users' => 'Pengguna',
    'Visible' => 'Ditampilkan',
];
