<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' does not support labels().' => '',
    '\'{class}\' must extend from \'yiibacRule\' or its child class' => '\'{class}\' must extend from \'yii\\r
bacRule\' or its child class',
    'Activate' => '',
    'Active' => '',
    'Add' => '',
    'All User' => '',
    'Application' => '',
    'Are you sure to delete this item?' => '',
    'Are you sure you want to {label} this user?' => '',
    'Assign' => '',
    'Assignment' => '',
    'Assignments' => '',
    'Auth Key' => '',
    'Change' => '',
    'Change Password' => '',
    'Check your email for further instructions.' => '',
    'Class Name' => '',
    'Create' => '',
    'Create Menu' => '',
    'Create Rule' => '',
    'Create {value}' => '',
    'Created At' => '',
    'Data' => '',
    'Delete' => '',
    'Description' => '',
    'Display Name' => '',
    'Email' => '',
    'Guide' => '',
    'ID' => '',
    'Icon' => '',
    'Inactive' => '',
    'Incorrect password.' => '',
    'Incorrect username or email.' => '',
    'Invalid rule "{value}"' => '',
    'Last Login' => '',
    'Login' => '',
    'Loop detected.' => '',
    'Menus' => '',
    'Name' => '',
    'New password was saved.' => '',
    'New route(s)' => '',
    'Non Activate' => '',
    'Order' => '',
    'Parent' => '',
    'Parent Name' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Permission' => '',
    'Permissions' => '',
    'Photo' => '',
    'Please choose your new password:' => '',
    'Please fill out the following fields to change password:' => '',
    'Please fill out the following fields to signup:' => '',
    'Please fill out your email. A link to reset password will be sent there.' => '',
    'RBAC' => '',
    'Remove' => '',
    'Request password reset' => '',
    'Reset password' => '',
    'Role' => '',
    'Roles' => '',
    'Route' => '',
    'Route "{value}" not found.' => '',
    'Routes' => '',
    'Rule "{value}" does not exists' => '',
    'Rule Name' => '',
    'Rules' => '',
    'Save' => '',
    'Search for assigned' => '',
    'Search for available' => '',
    'Send' => '',
    'Signup' => '',
    'Sorry, we are unable to reset password for email provided.' => '',
    'Status' => '',
    'The requested page does not exist.' => '',
    'Type' => '',
    'Unknown class \'{class}\'' => '',
    'Update' => '',
    'Update Menu' => '',
    'Update Rule' => '',
    'Update {value}' => '',
    'Updated At' => '',
    'User Login' => '',
    'User Not Login' => '',
    'Username' => '',
    'Users' => '',
    'Visible' => '',
];
