# GitHub Actions Workflow for Yii2 Toastr
# Tests across multiple PHP versions with code quality checks
#
# @link https://github.com/wanforge
# @author Sugeng Sulistiyawan
# @copyright Copyright (c) 2018-2025

name: Tests

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1, 8.2, 8.3]
        prefer-lowest: [false]
        include:
          - php-version: 7.4
            prefer-lowest: true
        
    name: PHP ${{ matrix.php-version }} ${{ matrix.prefer-lowest && '(prefer-lowest)' || '' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, pcov
        coverage: pcov
        tools: composer:v2
        
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.prefer-lowest && 'lowest-' || '' }}${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.prefer-lowest && 'lowest-' || '' }}
          ${{ runner.os }}-php-${{ matrix.php-version }}-
          
    - name: Install dependencies
      run: |
        if [ "${{ matrix.prefer-lowest }}" == "true" ]; then
          composer update --prefer-lowest --prefer-dist --no-interaction
        else
          composer install --prefer-dist --no-interaction
        fi
      
    - name: Run test suite
      run: composer test:all
      
    - name: Run tests with coverage
      if: matrix.php-version == '8.1' && matrix.prefer-lowest == false
      run: composer test:coverage-clover

    - name: Upload coverage reports to Codecov
      if: matrix.php-version == '8.1' && matrix.prefer-lowest == false
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
      
  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, intl
        tools: composer:v2
        
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-8.1-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.1-
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
      
    - name: Run PHP CodeSniffer
      run: composer phpcs
      
    - name: Run PHP CS Fixer (dry run)
      run: composer cs
      
    - name: Run PHPStan
      run: composer phpstan
